### ISSUE TITLE
[BUG] TCode_Serial_Arudino,  pinmode(ANALOGUEPIN... but const int declared as ANALOGPIN

### ISSUE THREAD

**Issue by Slogolith** [Dreamer2345/Arduino_TCode_Parser#10]
TCode_Serial_Arudino.ino

pinmode(ANALOGUEPIN,

should be pinmode(**ANALOGPIN**,

**Comment by Dreamer2345** [comment]
Thank you for bringing this bug to my attention Ive fixed the issue.
